### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/who-unfollowed-me#10]
GitHub actions:

1. Linting
2. Automated Pypi releases (triggers on `workflow_dispatch` and `release`)
   1. Also add binary builds (pyinstaller) to upload to release
4. Binary building -> upload artifacts

**Comment by yagueto** [comment]
Hi! I would be interested in helping out with this issue.

**Comment by TechWiz-3** [comment]
Perfect 👌 
Shall I assign you the issue?

**Comment by yagueto** [comment]
Sure!

By the way, what do you mean with "Binary building -> upload artifacts"? Also, I understand that "add binary builds (pyinstaller) to upload to release" means to GitHub releases

**Comment by TechWiz-3** [comment]
It means building 'binary' or executable files that allow users without python to run the program on their respective platforms

**Comment by TechWiz-3** [comment]
Example: https://github.com/TechWiz-3/happy-jar-cli/blob/main/.github/workflows/build.yml
https://github.com/TechWiz-3/happy-jar-cli/actions/runs/3163786851

**Comment by TechWiz-3** [comment]
Hey man, I'm preparing for an exam rn. I will take it tomorrow. Hopefully the day after tomorrow I will be free to take a proper look.

Thanks 👍

**Comment by yagueto** [comment]
No worries, good luck with it! I'll open a PR soon
