### ISSUE TITLE
Fix CI flake8 errors

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/who-unfollowed-me#18]
Clean up the files and ensure they pass the CI checks

**Comment by rexdivakar** [comment]
Hey @TechWiz-3 i would like to take this up

**Comment by TechWiz-3** [comment]
I have changed pylint to flake8, this way you can run `poetry run flake8` locally 👍

**Comment by rexdivakar** [comment]
cool will work on it and get it fixed

**Comment by rexdivakar** [comment]
I have completed it but i'm unable to raise a PR, have u locked the settings for raising a pR ?

**Comment by TechWiz-3** [comment]
Thanks for your work!

**Comment by rexdivakar** [comment]
You're welcome

**Comment by hitblast** [comment]
@TechWiz-3 Could you please assign this to me? I hope I can take this issue down.

**Comment by TechWiz-3** [comment]
> Could you please assign this to me? I hope I can take this issue down.
Sure

> Oh by the way, the label needs to be changed from `hacktoberfest-accepted` to `hacktoberfest.`

Oops thanks

Also please respond on Discord regarding the `pypi-release` workflow, i had to remove the release asset upload as it was erroring out

**Comment by hitblast** [comment]
I guess this issue needs to be closed.

**Comment by TechWiz-3** [comment]
Thank you
