### ISSUE TITLE
Make `README.md` compatible with Pypi

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/who-unfollowed-me#21]
Make the README.md link to image links rather than file locations to allow Pypi to render the README properly.
https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/

In `setup.py` add the repos README as the `long_description` as required by Pypi

**Comment by rexdivakar** [comment]
Hey @TechWiz-3 i can work on this pls assign it to my name

**Comment by TechWiz-3** [comment]
Sure, if you need, you can refer to `happy-jar-cli` for this one 
https://raw.githubusercontent.com/TechWiz-3/happy-jar-cli/main/README.md
https://github.com/TechWiz-3/happy-jar-cli/blob/main/setup.py
