### ISSUE TITLE
Automatically load token and remove `--token` option

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/who-unfollowed-me#31]
Personally, I also have an opinion about the use of `--token` flag. I believe the CLI should automatically load the token even if the `--token` flag is not specified and read from `UNFOLLOW_TOKEN`. That can be another issue @TechWiz-3 if you want.

_Originally posted by @tintinthong in https://github.com/TechWiz-3/who-unfollowed-me/issues/29#issuecomment-1272768920_

- [ ] Automatically load token
- [ ] If successfully loaded ensure that `HEADERS` is assigned correctly
- [ ] If `UNFOLLOW_TOKEN` is empty or cannot be loaded, assign `HEADERS` to an empty dict

**Comment by Dinoosawruss** [comment]
Happy to take this if nobody else is working on it

**Comment by TechWiz-3** [comment]
Sure :) 💪

**Comment by TechWiz-3** [comment]
#40
