### ISSUE TITLE
Add config versioning to autoresolve breaking change

### ISSUE THREAD

**Issue by Dinoosawruss** [TechWiz-3/who-unfollowed-me#37]
Hi
*Happy to take and work on this issue*

To fix the breaking change in #34 a version could be added to the config, if the version is missing the config could be renamed and the new default one can be created so that it doesn't lead to unexpected crashes.

Think its best to rename the config and then create the default rather than just overwriting it incase someone did have some configuration done that they can copy and paste across

It would just need to be a simple `version=1` at the top that is then incremented whenever any changes to the config layout are made

**Comment by TechWiz-3** [comment]
#38
