### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/who-unfollowed-me#7]
Create `unfollow.toml` config file in `~/.unfollow/`

Allow the config file to dictate the following:

1. Theme... i.e. `panels, bubbles or simple`.
2. Allow changing of default emojis used in the regular style
3. Allow customization of all colored text that uses rich markup `[style here]` (initially just for the regular theme but for all themes if possible) - this can be done because instead of doing `console.print("[style here]text[/style here]", the previous text can be set as a default variable and if a config is loaded from `unfollow.toml` it can replace the default variable)

**Comment by TechWiz-3** [comment]
Maybe create a file called `text.py` that takes in the arguments and config file and formats text for all the other files

**Comment by Dinoosawruss** [comment]
Hey! Sounds interesting could I be assigned to this?

**Comment by Dinoosawruss** [comment]
Would you like the user to be stored in the `unfollow.toml` file as well as the other options?

**Comment by TechWiz-3** [comment]
Probably un-necessary, let's keep the config file as strictly for dictating styles 👍

**Comment by Dinoosawruss** [comment]
Should all be implemented PR is ready for review
