### ISSUE TITLE
Issue running locally

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/who-unfollowed-me#9]
Hey everybody, the current setup of the repo doesn't allow for local testing, I'm really sorry for this issue and will work to fix it ASAP. Suggestions or PRS are welcome for this issue as well.

**Comment by efi-sre** [comment]
@TechWiz-3 please assign me and add labels `hacktoberfest` I'm contribute with this issue thanks

**Comment by k1m0ch1** [comment]
hi @TechWiz-3 can you assign me to this issue ? I'm kinda solve this issue, please assign me and add labels `hacktoberfest` thank you

**Comment by Dinoosawruss** [comment]
If you're getting the same issue as me, which is that it cannot import `unfollow.*whatever*` just pop an `src.` on the front of those imports
Worked for me :)

**Comment by TechWiz-3** [comment]
Yeah, only problem is, when it's packaged and uploaded to pip, the imports will fail as there is no package installed called `src` only a package called `unfollow`

**Comment by TechWiz-3** [comment]
Also, I promise I will get to everyone's PRs but right now I've woken up to 6 across 2 repos so give me some time please 😅

**Comment by TechWiz-3** [comment]
This has been solved with #16 
Refer to the README for dev guidelines, any feedback is appreciated
